import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portal.ndesks.com/');
  await page.goto('https://portal.ndesks.com/login');
  await page.pause();
  await page.getByPlaceholder('john@example.com').click();
  await page.getByPlaceholder('john@example.com').fill('saadali.teczon+1@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('saad.ali');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.locator('li').filter({ hasText: 'Management' }).click();
  await page.getByRole('link', { name: 'People' }).click();
  await page.getByRole('button', { name: 'Add Employee' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByPlaceholder('Employee name').click();
  await page.getByPlaceholder('Employee name').fill('Dexter');
  await page.getByText('Profile Picture*UploadAllowed Max size of 10MbName*Email(optional)Select TeamSel').click();
  await page.getByPlaceholder('Employee email').click();
  await page.getByPlaceholder('Employee email').fill('saadali.teczon+23@gmail.com');
  await page.locator('select[name="team"]').selectOption('15');
  await page.locator('.css-tlfecz-indicatorContainer').click();
  await page.getByText('Teczon 3', { exact: true }).click();
  await page.locator('select[name="role"]').selectOption('15');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('tab', { name: 'Team' }).click();
  await page.getByRole('button', { name: 'Add Team' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByPlaceholder('Team name').click();
  await page.getByPlaceholder('Team name').fill('Devops2');
  await page.getByPlaceholder('Team email').click();
  await page.getByPlaceholder('Team email').fill('saadali.teczon+22@gmail.com');
  await page.getByPlaceholder('More Info . . .').click();
  await page.getByPlaceholder('More Info . . .').fill('for devops engineers');
  await page.locator('#package-locations svg').click();
  await page.locator('#package-locations svg').click();
  await page.locator('#package-locations svg').click();
  await page.locator('#react-select-3-option-2').click();
  await page.getByText('Teczon 3', { exact: true }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('link', { name: 'Workplace' }).click();
  await page.getByRole('button', { name: 'Add Location' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByPlaceholder('Location Name').click();
  await page.getByPlaceholder('Location Name').fill('Space for test2');
  await page.getByPlaceholder('Location Address').click();
  await page.getByPlaceholder('Location Address').fill('lahore');
  await page.getByPlaceholder('Description').click();
  await page.getByPlaceholder('Description').fill('w2were');
  await page.getByPlaceholder('Capacity').click();
  await page.getByPlaceholder('Capacity').fill('43');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.locator('li').filter({ hasText: 'Member' }).click();
  await page.locator('div').filter({ hasText: /^MemberListList$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Company' }).click();
  await page.getByPlaceholder('Company name').click();
  await page.getByPlaceholder('Company name').fill('teczon for Test3');
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByPlaceholder('Company email').click();
  await page.getByPlaceholder('Company email').fill('example9@gmail.com');
  await page.getByPlaceholder('Enter 11-15 Digits Phone Number').click();
  await page.getByPlaceholder('Enter 11-15 Digits Phone Number').fill('030376939333');
  await page.getByPlaceholder('Address').click();
  await page.getByPlaceholder('Address').fill('lahore');
  await page.getByPlaceholder('00000-0000000-0').click();
  await page.getByPlaceholder('00000-0000000-0').fill('3247556384645');
  await page.locator('div').filter({ hasText: /^FloorPlease Select Floordemo floor planhgdfgxzy floor plansdemo floor plan 30$/ }).locator('#employee').selectOption('13');
  await page.locator('div').filter({ hasText: /^Room TypePlease Select Room TypeDedicated DeskPrivate Office$/ }).locator('#employee').selectOption('1');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.locator('div').filter({ hasText: /^ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyu$/ }).getByRole('combobox').selectOption('56');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('tab', { name: 'Individuals' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.locator('div').filter({ hasText: /^Profile Picture\*UploadAllowed Max size of 10Mb$/ }).locator('#custom-button').click();
  await page.getByPlaceholder('Enter Name').click();
  await page.getByPlaceholder('Enter Name').fill('interii');
  await page.getByPlaceholder('Enter Email').click();
  await page.getByPlaceholder('Enter Email').fill('example+99@gmail.com');
  await page.getByPlaceholder('Enter 11-15 Digits Phone Number').click();
  await page.getByPlaceholder('Enter 11-15 Digits Phone Number').fill('030319197823');
  await page.getByPlaceholder('Enter Address').click();
  await page.getByPlaceholder('Enter Address').fill('lahore');
  await page.locator('div').filter({ hasText: /^FloorPlease Select Floordemo floor planhgdfgxzy floor plansdemo floor plan 30$/ }).locator('#employee').selectOption('10');
  await page.locator('div').filter({ hasText: /^Room TypePlease Select Room TypeDedicated DeskPrivate Office$/ }).locator('#employee').selectOption('1');
  await page.locator('input[name="cnicNo"]').click();
  await page.locator('input[name="cnicNo"]').fill('2345559873425');
  await page.locator('textarea[name="description"]').click();
  await page.locator('textarea[name="description"]').fill('for test purpose2');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('12');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByPlaceholder('Enter Email').click();
  await page.getByPlaceholder('Enter Email').fill('example98@gmail.com');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('div').filter({ hasText: /^ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyu$/ }).getByRole('combobox').selectOption('56');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.locator('li').filter({ hasText: 'Booking' }).click();
  await page.locator('div').filter({ hasText: /^BookingListList$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Booking' }).click();
  await page.getByLabel('Select Date:').fill('2023-11-15');
  await page.getByText('4:30 AM - 5:00 AM').click();
  await page.getByText('5:00 AM - 5:30 AM').click();
  await page.getByText('5:30 AM - 6:00 AM').click();
  await page.getByText('6:00 AM - 6:30 AM').click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByLabel('Individual').check();
  await page.locator('#individualSelect svg').click();
  await page.getByText('saad ali', { exact: true }).click();
  await page.getByText('4:30 AM - 5:00 AM').click();
  await page.getByText('5:00 AM - 5:30 AM').click();
  await page.getByText('5:30 AM - 6:00 AM').click();
  await page.getByText('6:00 AM - 6:30 AM').click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('link', { name: 'Packages' }).click();
  await page.getByRole('button', { name: 'Add Package' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByPlaceholder('Enter Package Name').click();
  await page.getByPlaceholder('Enter Package Name').fill('oiwexj');
  await page.getByPlaceholder('Enter Price').click();
  await page.getByPlaceholder('Enter Price').fill('3000');
  await page.getByPlaceholder('Enter Persons').click();
  await page.getByPlaceholder('Enter Persons').fill('23');
  await page.locator('#space-package-0 svg').click();
  await page.getByText('Meeting room 3', { exact: true }).dblclick();
  await page.getByText('Meeting Room 1', { exact: true }).dblclick();
  await page.getByText('Meeting room 2', { exact: true }).click();
  await page.locator('.css-1wy0on6 > div:nth-child(3)').click();
  await page.getByText('Saadali', { exact: true }).dblclick();
  await page.locator('.css-1wy0on6 > div:nth-child(3)').click();
  await page.locator('div:nth-child(3) > .css-8mmkcg').click();
  await page.getByText('demo meeting room 4', { exact: true }).click();
  await page.locator('.css-1wy0on6 > div:nth-child(3)').click();
  await page.locator('.css-1wy0on6 > div:nth-child(3)').click();
  await page.getByText('qwerty2', { exact: true }).click();
  await page.locator('#durations svg').click();
  await page.locator('#react-select-10-option-2').click();
  await page.locator('div').filter({ hasText: /^Space Type\*Select\.\.\.$/ }).locator('svg').click();
  await page.locator('#react-select-11-option-0').click();
  await page.locator('#package-facilities svg').click();
  await page.getByText('All', { exact: true }).click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('button', { name: 'Add Meeting Package' }).click();
  await page.getByPlaceholder('Enter Meeting Package Name').click();
  await page.getByPlaceholder('Enter Meeting Package Name').fill('tester package3');
  await page.getByPlaceholder('Enter Price').click();
  await page.getByPlaceholder('Enter Price').fill('3000');
  await page.locator('#expiryDuration svg').click();
  await page.locator('#react-select-13-option-1').click();
  await page.locator('.css-1gtu0rj-indicatorContainer').click();
  await page.locator('#react-select-13-option-2').click();
  await page.locator('#space-package-0 svg').click();
  await page.getByText('Meeting Room 1', { exact: true }).click();
  await page.getByText('Meeting room 2', { exact: true }).click();
  await page.getByText('Meeting room 3', { exact: true }).click();
  await page.getByText('Saadali', { exact: true }).click();
  await page.getByText('demo meeting room 4', { exact: true }).click();
  await page.getByText('qwerty2', { exact: true }).click();
  await page.getByPlaceholder('1').click();
  await page.getByPlaceholder('1').fill('32');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('link', { name: 'Floor Plans' }).click();
  await page.getByRole('button', { name: 'Add Floor Plans' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByPlaceholder('Enter floor plan name').click();
  await page.getByPlaceholder('Enter floor plan name').fill('Ground floor');
  await page.getByPlaceholder('Enter capacity').click();
  await page.getByPlaceholder('Enter capacity').fill('12');
  await page.locator('#package-facilities svg').click();
  await page.getByText('All', { exact: true }).click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByText('id-cardVisitors').click();
  await page.locator('div').filter({ hasText: /^id-cardVisitorsListListRegistrationRegistration$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Add Visit' }).click();
  await page.getByRole('link', { name: 'Add New Visitor' }).click();
});