//Concurrency Testing: Simulate simultaneous access by multiple users to validate system behavior.
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portal.ndesks.com/');
  await page.goto('https://portal.ndesks.com/login');
  await page.getByPlaceholder('john@example.com').click();
  await page.getByPlaceholder('john@example.com').fill('saadali.teczon+81@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('saad.ali');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.pause();
  await page.locator('li').filter({ hasText: 'Management' }).click();
  await page.getByRole('link', { name: 'People' }).click();
  await page.getByRole('row', { name: 'ali ahmad example@gmail.com' }).getByRole('button').nth(1).click();
  await page.locator('select[name="role"]').selectOption('22');
  await page.locator('select[name="status"]').selectOption('2');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('link', { name: 'Workplace' }).click();
  await page.getByRole('tab', { name: 'Roles and Permissions' }).click();
  await page.getByRole('link', { name: 'Add Role' }).click();
  await page.getByLabel('Name*').click();
  await page.getByLabel('Name*').fill('guest-visit');
  await page.locator('.css-1d8n9bt').first().click();
  await page.getByText('Read', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^LocationsSelect\.\.\.$/ }).locator('svg').click();
  await page.getByText('None', { exact: true }).click();
  await page.locator('div:nth-child(3) > div > .css-b62m3t-container > .css-18za3vu-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click();
  await page.locator('#react-select-7-option-2').click();
  await page.locator('div').filter({ hasText: /^LocationsNone$/ }).locator('svg').nth(2).click();
  await page.getByLabel('Remove None').click();
  await page.locator('#react-select-6-option-2').click();
  await page.getByText('Meeting Room Management').click();
  await page.getByText('Peoples\' Management').click();
  await page.locator('.css-tlfecz-indicatorContainer').first().click();
  await page.getByText('Read', { exact: true }).click();
  await page.locator('.css-tlfecz-indicatorContainer').first().click();
  await page.getByText('None', { exact: true }).click();
  await page.locator('div:nth-child(3) > div > .css-b62m3t-container > .css-18za3vu-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click();
  await page.getByText('Write', { exact: true }).click();
  await page.locator('.col-md-12 > .row > .col-md-12 > div').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.locator('.mx-2').first().click();
  await page.getByPlaceholder('Capacity').click();
  await page.getByPlaceholder('Capacity').fill('12');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.locator('li').filter({ hasText: 'Invoice' }).click();
  await page.locator('div').filter({ hasText: /^InvoiceListListAddAdd$/ }).getByRole('link').first().click();
  await page.locator('li').filter({ hasText: 'Member' }).click();
  await page.locator('div').filter({ hasText: /^MemberListList$/ }).getByRole('link').click();
  await page.locator('div').filter({ hasText: /^InvoiceListListAddAdd$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Create Invoice' }).click();
  await page.locator('div').filter({ hasText: /^Select\.\.\.$/ }).nth(2).click();
  await page.getByText('ahmad', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('li').filter({ hasText: 'Booking' }).click();
  await page.locator('div').filter({ hasText: /^BookingListList$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Booking' }).click();
  await page.getByText('Individual').click();
  await page.locator('.css-ackcql').first().click();
  await page.getByText('saad ali', { exact: true }).click();
  //await page.getByText('6:30 PM - 7:00 PM').click();
  await page.getByText('7:00 PM - 7:30 PM').click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('link', { name: 'Packages' }).click();
  await page.getByRole('link', { name: 'Floor Plans' }).click();
  await page.getByRole('link', { name: 'Packages' }).click();
  await page.getByRole('button', { name: 'Add Package' }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('link', { name: 'Floor Plans' }).click();
  await page.getByRole('row', { name: 'demo meeting room 4' }).getByRole('button').nth(1).click();
  await page.getByPlaceholder('Enter Capacity').click();
  await page.getByPlaceholder('Enter Capacity').fill('12');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.locator('li').filter({ hasText: 'Quotation' }).click();
  await page.locator('div').filter({ hasText: /^QuotationListListAddAdd$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Add Quotation' }).click();
  await page.getByPlaceholder('Postal Code/ZIP Code').click();
  await page.getByPlaceholder('Postal Code/ZIP Code').fill('42000');
  await page.getByPlaceholder('Your Business/Freelancer Name Required').click();
  await page.getByPlaceholder('Your Business/Freelancer Name Required').fill('saadali');
  await page.getByPlaceholder('Address (Optional)').click();
  await page.getByPlaceholder('Address (Optional)').fill('lahore');
  await page.getByPlaceholder('Email (required)').click();
  await page.getByPlaceholder('Email (required)').fill('saadali.teczon+88@gmail.com');
  await page.getByPlaceholder('11-15 Digits Phone Number').click();
  await page.getByPlaceholder('11-15 Digits Phone Number').fill('30328827257');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByText('id-cardVisitors').click();
  await page.locator('div').filter({ hasText: /^id-cardVisitorsListListRegistrationRegistration$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Add Visit' }).click();
  await page.getByRole('button', { name: 'Add Visit' }).click();
  await page.getByRole('button', { name: 'Add Visit' }).click();
  await page.getByRole('link', { name: 'Add New Visitor' }).click();
  await page.locator('input[name="expected_visit_datetime"]').click();
  await page.locator('input[name="expected_visit_datetime"]').click();
  await page.getByPlaceholder('Enter Visitor\'s Name').click();
  await page.getByPlaceholder('Enter Visitor\'s Name').fill('Thor');
  await page.getByPlaceholder('Enter Visitor\'s Company').click();
  await page.getByPlaceholder('Enter Visitor\'s Company').fill('Earth');
  await page.getByPlaceholder('Enter Visitor\'s Email').click();
  await page.getByPlaceholder('Enter Visitor\'s Email').fill('exampl2@gmail.com');
  await page.getByPlaceholder('Enter Visitor\'s Phone No').click();
  await page.getByPlaceholder('Enter Visitor\'s Phone No').fill('030328282726');
  await page.getByPlaceholder('Person You Are Visiting').click();
  await page.getByPlaceholder('Person You Are Visiting').fill('ali');
  await page.getByPlaceholder('Purpose of Visit').click();
  await page.getByPlaceholder('Purpose of Visit').fill('meeting');
  await page.locator('input[name="expected_visit_datetime"]').click();
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowLeft');
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowLeft');
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowLeft');
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowLeft');
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowLeft');
  await page.locator('input[name="expected_visit_datetime"]').fill('');
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowLeft');
  await page.locator('input[name="expected_visit_datetime"]').press('ArrowRight');
  await page.locator('input[name="expected_visit_datetime"]').fill('2023-12-23T12:34:02');
  await page.getByPlaceholder('Enter Location').click();
  await page.getByPlaceholder('Enter Location').fill('lahore');
  await page.getByRole('button', { name: 'Add Visitor' }).click();
  await page.getByRole('link', { name: 'Partner & Offers' }).click();
  await page.getByRole('button', { name: 'Create Partner' }).click();
  await page.getByLabel('Category*').selectOption('7');
  await page.getByPlaceholder('Enter a name').click();
  await page.getByPlaceholder('Enter a name').fill('qwwerty');
  await page.getByPlaceholder('Enter a  contact name').click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('button', { name: 'Create Offer' }).click();
  await page.getByPlaceholder('Add a discount').click();
  await page.getByPlaceholder('Add a discount').fill('13');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.locator('li').filter({ hasText: 'Tours' }).click();
  await page.locator('div').filter({ hasText: /^ToursListListRegistrationRegistration$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Add Tour' }).click();
  await page.getByPlaceholder('Enter your name').click();
  await page.getByPlaceholder('Enter your name').fill('ahmad');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('ahmad@gmail.com');
  await page.getByPlaceholder('Enter your phone number').click();
  await page.getByPlaceholder('Enter your phone number').fill('123123123123');
  //await page.frameLocator('iframe[name="a-ota9r2847uq4"]').getByLabel('I\'m not a robot').click();
  await page.getByRole('link', { name: 'Tickets' }).click();
  await page.getByRole('button', { name: 'Add Ticket' }).click();
  await page.getByPlaceholder('Enter purpose').click();
  await page.getByLabel('Category', { exact: true }).selectOption('4');
  await page.getByPlaceholder('Enter purpose').click();
  await page.getByPlaceholder('Enter purpose').fill('lkadjkald');
  await page.getByPlaceholder('Enter description').click();
  await page.getByPlaceholder('Enter description').fill('asfasdw');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.locator('#dropdown-notification').click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByPlaceholder('john@example.com').click();
  await page.getByPlaceholder('john@example.com').fill('saadali.teczon+82@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('saad.ali');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Tickets' }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByLabel('Main Category').selectOption('7');
  await page.getByLabel('Category', { exact: true }).selectOption('13');
  await page.getByLabel('Category', { exact: true }).selectOption('9');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('link', { name: 'Partner & Offers' }).click();
  await page.locator('#dropdown-basic').first().click();
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByText('id-cardVisitors').click();
  await page.locator('div').filter({ hasText: /^id-cardVisitorsListListRegistrationRegistration$/ }).getByRole('link').first().click();
//   await page.getByRole('row', { name: 'Thor exampl2@gmail.com' }).locator('a').click();
//   await page.getByRole('button', { name: 'Update Visit' }).click();
//   await page.getByRole('row', { name: 'Thor exampl2@gmail.com' }).locator('button').click();
//   await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('li').filter({ hasText: 'Quotation' }).click();
  await page.locator('div').filter({ hasText: /^QuotationListListAddAdd$/ }).getByRole('link').first().click();
  await page.getByRole('button').nth(2).click();
  await page.getByPlaceholder('Your Business/Freelancer Name Required').click();
  await page.getByPlaceholder('Your Business/Freelancer Name Required').fill('saadali123');
  await page.getByRole('button', { name: 'Update & Continue' }).click();
//   await page.getByRole('cell', { name: 'View Quotation' }).locator('button').click();
//   await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByRole('link', { name: 'Floor Plans' }).click();
  await page.getByRole('link', { name: 'Packages' }).click();
  await page.locator('li').filter({ hasText: 'Booking' }).click();
  await page.locator('div').filter({ hasText: /^BookingListList$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Booking' }).click();
  await page.getByText('Individual').click();
  await page.locator('.css-ackcql').first().click();
  await page.getByText('saad ali', { exact: true }).click();
  await page.getByText('8:30 PM - 9:00 PM').click();
  await page.getByText('9:00 PM - 9:30 PM').click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByLabel('Close').click();
  await page.locator('li').filter({ hasText: 'Member' }).click();
  await page.locator('div').filter({ hasText: /^MemberListList$/ }).getByRole('link').click();
  await page.getByRole('tab', { name: 'Individuals' }).click();
  await page.getByRole('row', { name: 'Thor saadali.teczon+53@gmail.com' }).locator('a').click();
  await page.getByRole('tab', { name: 'Pending' }).click();
  await page.getByRole('tab', { name: 'History' }).click();
  await page.getByRole('tab', { name: 'Pending' }).click();
  await page.getByRole('tab', { name: 'Active' }).click();
  await page.getByRole('button', { name: 'Add Package' }).click();
  await page.locator('div').filter({ hasText: /^ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewoiwedj$/ }).getByRole('combobox').selectOption('58');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.locator('li').filter({ hasText: /^Invoice$/ }).click();
  await page.locator('div').filter({ hasText: /^InvoiceListListAddAdd$/ }).getByRole('link').first().click();
  await page.getByText('Management').click();
  await page.getByRole('link', { name: 'People' }).click();
  await page.getByRole('link', { name: 'Workplace' }).click();
  await page.locator('.mx-2').first().click();
  await page.getByPlaceholder('Location Name').click({clickCount: 3});
  await page.getByPlaceholder('Location Name').fill('test space');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
});