//test case for negative inputs
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portal.ndesks.com/');
  await page.goto('https://portal.ndesks.com/login');
  await page.getByPlaceholder('john@example.com').click();
  await page.getByPlaceholder('john@example.com').fill('saadali.teczon+1@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('saad.ali');
  await page.getByLabel('Password').press('Enter');
  await page.pause();
  await page.goto('https://portal.ndesks.com/');
  await page.locator('li').filter({ hasText: 'Management' }).click();
  await page.getByRole('link', { name: 'People' }).click();
  await page.getByRole('button', { name: 'Add Employee' }).click();
  await page.getByPlaceholder('Employee name').click();
  await page.getByPlaceholder('Employee name').fill('Saad Ali');
  await page.getByPlaceholder('Employee email').click();
  await page.getByPlaceholder('Employee email').fill('saadali.teczon+1@gmail.com');
  await page.locator('#package-locations svg').click();
  await page.getByText('Space for test', { exact: true }).click();
  await page.locator('#package-locations path').nth(1).click();
  await page.getByText('Space for test', { exact: true }).click();
  await page.locator('#package-locations svg').nth(2).click();
  await page.locator('select[name="role"]').selectOption('15');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
//  await page.getByRole('button', { name: 'Upload' }).setInputFiles('groot1.jpg');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('tab', { name: 'Team' }).click();
  await page.getByRole('button', { name: 'Add Team' }).click();
  await page.getByPlaceholder('Team name').click();
  await page.getByPlaceholder('Team name').fill('Devops');
  await page.getByPlaceholder('Team email').click();
  await page.getByPlaceholder('Team email').fill('example@gmail.com');
  await page.getByPlaceholder('More Info . . .').click();
  await page.getByPlaceholder('More Info . . .').fill('for testing');
  await page.locator('.css-ackcql').click();
  await page.getByText('Space for test', { exact: true }).click();
  await page.locator('#package-locations svg').nth(2).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  //await page.getByRole('button', { name: 'Upload' }).setInputFiles('groot1.jpg');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByPlaceholder('Team email').click();
  await page.getByPlaceholder('Team email').click();
  await page.getByPlaceholder('Team email').fill('example123@gmail.com');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByText('Close').click();
  await page.getByRole('link', { name: 'Workplace' }).click();
  await page.getByRole('tab', { name: 'Roles and Permissions' }).click();
  await page.getByLabel('Roles and Permissions').locator('#viewMeetingOpen').nth(3).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByRole('tab', { name: 'Location' }).click();
  await page.locator('div:nth-child(1) > div > .d-flex > div > #viewMeetingOpen').click();
  await page.getByRole('button', { name: 'No, cancel!' }).click();
  await page.locator('.card > div > .d-flex > div > #viewMeetingOpen').first().click();
  await page.getByRole('button', { name: 'No, cancel!' }).click();
  await page.locator('li').filter({ hasText: 'Invoice' }).click();
  await page.locator('div').filter({ hasText: /^InvoiceListListAddAdd$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Create Invoice' }).click();
  await page.locator('div').filter({ hasText: /^Invoice To:Select\.\.\.$/ }).locator('svg').click();
  await page.getByText('ahmad', { exact: true }).click();
//   await page.locator('form').filter({ hasText: 'ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyuoiwedjCostquantity' }).getByPlaceholder('1').click();
//   await page.locator('form').filter({ hasText: 'ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyuoiwedjCostquantity' }).getByPlaceholder('1').click();
//   await page.locator('form').filter({ hasText: 'ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyuoiwedjCostquantity' }).getByPlaceholder('1').click();
//   await page.locator('form').filter({ hasText: 'ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyuoiwedjCostquantity' }).getByPlaceholder('1').click();
//   await page.locator('form').filter({ hasText: 'ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyuoiwedjCostquantity' }).getByPlaceholder('1').fill('-1223');
  //await page.locator('form').filter({ hasText: 'ItemHot Deskdemo-packageSaad Alidemo-floor-plan-2sffseewsrybyuoiwedjCostquantity' }).getByRole('button').click();
  //await page.locator('form').filter({ hasText: 'ItemMeeting pkg2xyz meetingtester packageCostquantityPrice3000Add Item' }).getByRole('img').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Add' }).first().click();
  await page.locator('li').filter({ hasText: 'Member' }).click();
  await page.locator('div').filter({ hasText: /^MemberListList$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Company' }).click();
  await page.getByPlaceholder('Company name').click();
  await page.getByPlaceholder('Company name').fill('teczon 2.0');
  await page.getByPlaceholder('Company email').click();
  await page.getByPlaceholder('Company email').fill('saadali.teczon+11@gmail.com');
  await page.getByPlaceholder('Enter 11-15 Digits Phone Number').click();
  await page.getByPlaceholder('Enter 11-15 Digits Phone Number').fill('123123123123');
  await page.getByPlaceholder('Address').click();
  await page.getByPlaceholder('Address').fill('lahore');
  await page.getByPlaceholder('00000-0000000-0').click();
  await page.getByPlaceholder('00000-0000000-0').fill('23411123234456');
  await page.locator('#employee').first().selectOption('10');
  await page.locator('div').filter({ hasText: /^Room TypePlease Select Room TypeDedicated DeskPrivate Office$/ }).locator('#employee').selectOption('1');
  //await page.getByRole('button', { name: 'Add Company', exact: true }).click();
  await page.getByPlaceholder('00000-0000000-0').click();
  await page.getByPlaceholder('00000-0000000-0').fill('234111232344561');
  await page.getByRole('button', { name: 'Add Company', exact: true }).click();
  await page.getByPlaceholder('00000-0000000-0').click();
  await page.getByPlaceholder('00000-0000000-0').fill('234111232344');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByPlaceholder('00000-0000000-0').click();
  await page.getByPlaceholder('00000-0000000-0').fill('3241112323456');
  await page.getByRole('button', { name: 'Add Company', exact: true }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  //await page.getByRole('button', { name: 'Upload' }).setInputFiles('groot1.jpg');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('tab', { name: 'Individuals' }).click();
  await page.getByRole('row', { name: 'ahmad saadali.teczon+8@gmail.com' }).locator('button').click();
  await page.getByRole('button', { name: 'No, cancel!' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.locator('div').filter({ hasText: /^Save$/ }).click();
  await page.getByLabel('Close').click();
  await page.locator('li').filter({ hasText: 'Booking' }).click();
  await page.locator('div').filter({ hasText: /^BookingListList$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Add Booking' }).click();
  await page.getByLabel('Individual').check();
  await page.locator('.css-ackcql').first().click();
  await page.locator('#react-select-12-option-4').click();
  await page.getByLabel('Capacity').click();
  await page.getByLabel('Capacity').fill('123');
  await page.getByText('9:00 PM - 9:30 PM').click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByLabel('Close').click();
  await page.getByRole('link', { name: 'Packages' }).click();
  await page.getByRole('row', { name: 'Saad Ali' }).getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'No, cancel!' }).click();
//   await page.getByRole('row', { name: 'xyz meeting 12334 43 Daily' }).getByRole('button').nth(2).click();
//   await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByRole('link', { name: 'Floor Plans' }).click();
  await page.locator('div:nth-child(2) > div > .d-flex > div:nth-child(3) > .p-0').click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('li').filter({ hasText: 'Quotation' }).click();
  await page.locator('div').filter({ hasText: /^QuotationListListAddAdd$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Add Quotation' }).click();
  await page.locator('section').getByRole('button').first().click();
  await page.locator('section').getByRole('button').nth(1).click();
  await page.locator('select[name="customer\\.country"]').selectOption('Pakistan');
  await page.locator('#state').selectOption('Punjab');
  await page.locator('select[name="customer\\.cityName"]').selectOption('Lahore');
  await page.getByPlaceholder('Postal Code/ZIP Code').click();
  await page.getByPlaceholder('Postal Code/ZIP Code').fill('52000');
  await page.getByPlaceholder('Your Business/Freelancer Name Required').click();
  await page.getByPlaceholder('Your Business/Freelancer Name Required').fill('saad ali');
  await page.getByPlaceholder('Email (required)').click();
  await page.getByPlaceholder('Email (required)').fill('saadali.teczon+1@gmail.com');
  await page.getByPlaceholder('11-15 Digits Phone Number').click();
  await page.getByPlaceholder('11-15 Digits Phone Number').fill('030312321232');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByText('id-cardVisitors').click();
  await page.locator('div').filter({ hasText: /^id-cardVisitorsListListRegistrationRegistration$/ }).getByRole('link').first().click();
  await page.getByRole('link', { name: 'Registration' }).first().click();
  await page.getByRole('link', { name: 'Add New Visitor' }).click();
  await page.locator('input[name="expected_visit_datetime"]').click();
  await page.locator('#root div').filter({ hasText: 'NameCompanyEmailContact NumberPerson You Are VisitingReason of VisitingDate and ' }).nth(1).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Partner & Offers' }).click();
  await page.locator('li').filter({ hasText: 'Tours' }).click();
  await page.locator('div').filter({ hasText: /^ToursListListRegistrationRegistration$/ }).getByRole('link').first().click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('link', { name: 'Tickets' }).click();
});