//test case for tickets add with spaceowner members and with missing fields and delete all of that
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://portal.ndesks.com/');
  await page.goto('https://portal.ndesks.com/login');
  await page.getByPlaceholder('john@example.com').click();
  await page.getByPlaceholder('john@example.com').fill('saadali.teczon+1@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('saad.ali');
  await page.getByLabel('Password').press('Enter');
  await page.pause();
  await page.getByRole('link', { name: 'Tickets' }).click();
  await page.getByRole('button', { name: 'Add Ticket' }).click();
  await page.getByLabel('Member').selectOption('52');
  await page.getByLabel('Main Category').selectOption('24');
  await page.getByPlaceholder('Enter purpose').click();
  await page.getByPlaceholder('Enter purpose').fill('the invoice is incorrect');
  await page.getByPlaceholder('Enter description').click();
  await page.getByPlaceholder('Enter description').fill('the ammount that are in invoice is incorrect');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.locator('#dropdown-notification').click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.locator('html').click();
  await page.getByPlaceholder('john@example.com').click();
  await page.getByPlaceholder('john@example.com').fill('saadali.teczon+95@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('saad.ali');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('ndesks123@');
  await page.getByLabel('Password').press('Enter');
  await page.getByRole('link', { name: 'Tickets' }).click();
  await page.getByRole('button', { name: 'Add Ticket' }).click();
  await page.getByLabel('Member').selectOption('53');
  await page.getByPlaceholder('Enter purpose').click();
  await page.getByPlaceholder('Enter purpose').fill('there is a covid symptoms in the employee');
  await page.getByPlaceholder('Enter description').click();
  await page.getByPlaceholder('Enter description').fill('Imposter have the covid symptoms find him');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('row', { name: 'saad ali' }).getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByPlaceholder('Enter description').click();
  await page.getByPlaceholder('Enter description').fill('Imposter have the covid symptoms find him/her');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button').nth(4).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
});